%%% ==================================================================
%%% this file is generated by tools. do not edit it by yourself.
%%% ==================================================================

-module(proto_api).
-compile(export_all).
-include("proto_api.hrl").

key(code_ack) -> ?API_CODE_ACK;
key(login_req) -> ?API_LOGIN_REQ;
key(snapshot_ack) -> ?API_SNAPSHOT_ACK;
key(building_up_req) -> ?API_BUILDING_UP_REQ;
key(_) -> xx.